services:
  - type: web
    name: CarbonWise-Backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: Bearer_API_Key
        fromEnvVar: Bearer_API_Key
      - key: Rapid_API_Key
        fromEnvVar: Rapid_API_Key
