services:
  - type: web
    name: carbon-wise-backend
    env: java
    plan: free
    runtime: manual
    buildCommand: ./mvnw clean package
    startCommand: java -jar CarbonWise.jar
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/.render_home/java
      - key: Bearer_API_Key
        fromEnvVar: Bearer_API_Key
      - key: Rapid_API_Key
        fromEnvVar: Rapid_API_Key
