### GET request to example server

// Business Entity
GET http://localhost:8080/businesses

###
GET http://localhost:8080/businesses/2

###
POST http://localhost:8080/businesses/addBusiness
Content-Type: application/json

{
  "name": "MAGA",
  "industry": "Construction",
  "location": "Colombo",
  "country": "Sri Lanka"
}
###
PUT http://localhost:8080/businesses/updateBusiness
Content-Type: application/json

{
  "id": 3,
  "name": "MAGA",
  "industry": "Construction",
  "location": "Nawala",
  "country": "Sri lanka"
}
###
DELETE http://localhost:8080/businesses/2

###


