### GET request to example server
// EmissionEntry Entity
GET http://localhost:8080/emission_entries

###
GET http://localhost:8080/emission_entries/getEmissionEntryByUserId/3

###
POST http://localhost:8080/emission_entries/addEmissionEntry
Content-Type: application/json

{
  "type": "Waste",
  "data": "Organic/Food",
  "method": "Landfilled",
  "amount": 1025,
  "unit": "kg",
  "date": "2025-06-20",
  "user": {
    "id": 3,
    "name": "Mike",
    "email": "mike@gmail.com",
    "password": "mk457",
    "role": "employee",
    "business": {
      "id": 3,
      "name": "MAGA",
      "industry": "Construction",
      "location": "Nawala",
      "country": "Sri Lanka"
    }
  }
}
###
PUT http://localhost:8080/emission_entries/updateEmissionEntry
Content-Type: application/json

{
  "id": 55,
  "type": "Waste",
  "data": "Organic/Food",
  "method": "Landfilled",
  "amount": 975,
  "unit": "kg",
  "date": "2025-06-27",
  "user": {
    "id": 3,
    "name": "Mike",
    "email": "mike@gmail.com",
    "password": "mk457",
    "role": "employee",
    "business": {
      "id": 3,
      "name": "MAGA",
      "industry": "Construction",
      "location": "Nawala",
      "country": "Sri Lanka"
    }
  }
}
###
DELETE http://localhost:8080/emission_entries/49

###
POST https://www.carboninterface.com/api/v1/estimates
Authorization: Bearer Carbon_API_Key
Content-Type: application/json

{
    "type": "electricity",
    "electricity_unit": "mwh",
    "electricity_value": 42,
    "country": "sl"
}
###