### GET request to example server
GET http://localhost:8080/businesses

###
GET http://localhost:8080/businesses/2

###
POST http://localhost:8080/businesses
Content-Type: application/json

{
  "name": "Moose",
  "industry": "Clothing",
  "location": "Colombo"
}
###
PUT http://localhost:8080/businesses
Content-Type: application/json

{
  "id": 2,
  "name": "Moose",
  "industry": "Clothing",
  "location": "Ja-Ela"
}
###
DELETE http://localhost:8080/businesses/2

###

