### GET request to example server

// User Entity
GET http://localhost:8080/users

###
GET http://localhost:8080/users/2

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "nimal123@gmail.com",
  "password": "nimal123",
  "role": "employee",
  "business": {
    "id": 1,
    "name": "WSO2",
    "industry": "Software",
    "location": "Colombo"
  }
}
###
PUT http://localhost:8080/users
Content-Type: application/json

{
  "id": 2,
  "email": "nimal123@gmail.com",
  "password": "nimal123",
  "role": "employee",
  "business": {
    "id": 1,
    "name": "WSO2",
    "industry": "Software",
    "location": "Colombo"
  }
}
###
DELETE http://localhost:8080/users/2

###