### GET request to example server

// User Entity
GET http://localhost:8080/users

###
GET http://localhost:8080/users/2

###
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "name": "Mike",
  "email": "mike@gmail.com",
  "password": "mk457",
  "role": "employee",
  "business": {
    "id": 3,
    "name": "MAGA",
    "industry": "Contruction",
    "location": "Nawala",
    "country": "Sri Lanka"
  }
}
###
PUT http://localhost:8080/users/updateUser
Content-Type: application/json

{
  "id": 3,
  "name": "Mike",
  "email": "mike@gmail.com",
  "password": "mk457",
  "role": "employee",
  "business": {
    "id": 3,
    "name": "MAGA",
    "industry": "Construction",
    "location": "Nawala",
    "country": "Sri Lanka"
  }
}
###
DELETE http://localhost:8080/users/2

###