name: Build and Push Docker Image

on:
  push:
    branches: [main]

env:
  Image_Path: ${{ vars.Image_Path }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag image
        run: |
          docker build \
            --build-arg Database_Host=${{ secrets.Database_Host }} \
            --build-arg Database_Username=${{ secrets.Database_Username }} \
            --build-arg Database_Password=${{ secrets.Database_Password }} \
            --build-arg Bearer_API_Key=${{ secrets.Bearer_API_Key }} \
            --build-arg Rapid_API_Key=${{ secrets.Rapid_API_Key }} \
            --build-arg Open_AI_Key=${{ secrets.Open_AI_Key }} \
            -t ${{ env.Image_Path }} .

      - name: Push image
        run: |
          docker push ${{ env.Image_Path }}
