name: Build and Push Docker Image

on:
  push:
    branches: [main]

env:
  IMAGE_TAG: ${{ vars.IMAGE_TAG }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_TAG }} .

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_TAG }}
